- frontend/src/tailwind.css
- frontend/tailwind.config.js
- 피그마의 theme를 tailwindcss에 설정함.
- `text-strong`과 같은 설정들을 theme color가 아니라 plugins로 주어서 text의 색깔을 바로 지정할 수 있게 함.
- theme color로 설정할 시에는 class 명을 `text-text-strong`과 같은 형식으로 주어야 함.
- 마찬가지로 `border-default`는 바로 border color로 `surface-default`는 바로 background 색깔을 지정하게 plugin으로 주었음.
```html
<>
<div className="w-full h-full bold24 text-weak surface-alt">123132</div>
</>
```
close #86
> Fe/feature/#86 tailwindcss theme 설정

- frontend/src/App.tsx
- frontend/src/components/BackgroundMusic/BackgroundMusic.tsx
- frontend/src/components/CustomButton/CustomButton.tsx
- frontend/src/components/Header/Header.tsx
- frontend/src/components/Header/HeaderLeft.tsx
- frontend/src/components/MessageBox/Message.tsx
- frontend/src/components/MessageBox/MessageBox.tsx
- frontend/src/components/MessageBox/index.ts
- frontend/src/pages/AIChatPage/AIChatPage.tsx
- frontend/src/pages/HomePage/HomePage.tsx
- frontend/tailwind.config.js
resolve #27
resolve #133 
- message 컴포넌트 구현
- messageBox 컴포넌트 구현
- 라우터 파라미터 id를 필수값이 아닌 선택값으로 변경
- 헤더 수정
- 뮤직 버튼 위치 수정
- tailwind 설정 추가
- 어두운 밑 배경과 fadein 애니메이션 적용
<br>
- 배경 이미지 부분이 계속 반복되는 거 같은데 묶어서 하나의 컴포넌트로 만들어보는게 좋을까?
```
<div className="w-screen h-screen flex flex-col justify-center items-center gap-80">
<img
className="absolute w-full h-full object-cover -z-10"
src="/bg.png"
alt="밤 하늘의 배경 이미지"
/>
<img
className="w-285 h-285 animate-shining relative bottom-130"
src="/moon.png"
alt="빛나는 마법의 소라 고둥"
/>
<div className="absolute w-full h-full bg-black/75 animate-fadeIn" />
```
<br>
https://github.com/boostcampwm2023/web09-MagicConch/assets/69742775/6ddecd41-a4f6-4377-baf5-a0fd4f4e9077
> Fe/feature/#27,133 ai 채팅 화면과 message box 컴포넌트 구현

- backend/src/chat/chat.controller.ts
- backend/src/chat/chat.service.ts
- backend/src/common/auth/auth.guard.ts
- backend/src/common/config/database/database.module.ts
- backend/src/tarot/dto/create-tarot-result.dto.ts
- backend/src/tarot/dto/tarot-card-response.dto.ts
- backend/src/tarot/dto/tarot-result-response.dto.ts
- backend/src/tarot/entities/tarot-card.entity.ts
- backend/src/tarot/entities/tarot-result.entity.ts
- backend/src/tarot/tarot.controller.ts
- backend/src/tarot/tarot.module.ts
- backend/src/tarot/tarot.service.ts
타로 관련 API 및 서비스 작성
아직 ObjectStorage와 클로바 스튜디오를 연결하지 않아 수정될 가능성이 높다.
**컨트롤러** 
- `GET /tarot/card/:id` : 카드 숫자가 id인 카드 이미지를 반환한다.
- `GET /tarot/result/:id` : 해당 ID의 타로 결과를 반환한다.
**서비스**
- `findTarotCardById` : 카드 번호가 id인 카드 이미지 URL을 반환한다.
- `createTarotResult` : 웹소켓에서 호출하게 되는 메서드로, 클로바 API 호출 후 그 결과를 `message`에 저장한다.
- `findTarotResultById` : 해당 ID의 타로 결과를 반환한다.
어제 작업물에서 `req` 객체에 쿠키가 붙어있는지 확인하는 코드가 중복으로 사용되는 게 마음에 걸려 해당 부분을 가드를 사용하여 수정했다.
```ts
...
@Injectable()
export class AuthGuard implements CanActivate {
canActivate(
context: ExecutionContext,
): boolean | Promise<boolean> | Observable<boolean> {
const req: Request = context.switchToHttp().getRequest();
if (!req.cookies.magicConch) { // AuthGuard에서 쿠키 여부 확인 -> 쿠키 없으면 UnauthorizedException 던짐
throw new UnauthorizedException();
} …
```
> Be/feature/#143 타로 api 및 서비스 구현

- backend/src/events/constants.ts
- backend/src/events/events.gateway.ts
- frontend/index.html
- frontend/src/business/hooks/useAiChat/useAiChatMessage.ts
- frontend/src/business/services/socket.ts
- frontend/src/components/ChatList/ChatList.tsx
- frontend/src/components/ChatList/index.ts
- frontend/src/components/MessageBox/Message.tsx
- frontend/src/components/MessageBox/MessageBox.tsx
- frontend/src/pages/AIChatPage/AIChatPage.tsx
resolve #169 
resolve #164
- MessageBox에 button 추가 가능 하도록 수정
- 타로 결과가 뜨고 어느정도 시간이 흐르고 나서 피드백 요구창이 뜨도록 함.
- told 스크립트를 index.html에 넣어둠. (호스트 네임이 유효하지 않아 error가 뜸 -> 배포 이후 진행 가능)
server에서 타로 해설 3초 이후에 `chatEnd` 이벤트를 발생시킨다.
`chatEnd` 이벤트가 발생하면 화면에 피드백을 요구하는 메세지가 띄워진다.
> Fe,be/feature/#169 #181 타로 해설 이후에 피드백 요구 told 도입

- frontend/src/pages/ResultSharePage/ResultSharePage.tsx
- 공유 결과 화면에서 suspense 제거
공유 결과 화면에서는 필요 없다고 판단함.
fallback이 있으면 오히려 사용자 경험이 나쁠거라 생각했기 때문.
이미지가 한장밖에 없어서 fallback -> 이동 하면 깜빡거릴 수 있음
> Fe/feature/#193 공유화면 fetch중일때 fallback처리

- frontend/src/components/TarotSpread/TarotCard.tsx
- frontend/src/components/TarotSpread/TarotSpread.tsx
resolve #41 
- 카드 선택 시 회전 및 확대
- 코드 가독성 개선
<br>
1️⃣ tailwind의 또 다른 문제점
```
🐞 문제
rotate3d의 기능을 제공하지 않음 
tailwind에서 제공하는 rotate-10 같은 방식은 2d 회전
찾아보니 tailwind는 이러한 3d기능은 보편적이지 않다고 판단해서 공식적으로는 지원하지 않는다고 함
플러그인을 사용하면 되는 것 같지만 적용이 제대로 되지 않음
해당 답변에 대한 댓글을 보니 나만 안되는건 아닌 것 같음 (하다가 포기했다는 반응이 대다수)
✅ 동적으로 style 객체에 설정을 추가함
우선 타켓 요소에 useRef를 걸어두고, 
애니메이션이 실행될 타이밍에 ref.style.transform = "rotateY(..)" 를 설정
transform 이외에도 다른 css를 개별적으로 모두 설정 가능
```
2️⃣ 회전 효과 주기
```
참고: https://solo5star.tistory.com/40
✅ 핵심 속성
- backface-visibility는 rotateY로 인해 180도 뒤집혔을 때 표시할 지 여부를 정하는 옵션
- transform: perspective는 3D 입체 효과를 주기 위한 원근감 옵션
- transform: rotateY는 Y축을 기준으로 회전하는 속성
✅ 카드 구조
<div class="card">
<div class="front">앞면</div>
<div class="back">뒷면</div>
</div>
✅ card에 적용
{
transition: transform 0.3s;
transform: …
```
> feat: 타로 카드 클릭 시 회전 효과 발생

- frontend/src/components/Background/Background.tsx
- frontend/src/components/CustomSelect/CustomSelect.tsx
- frontend/src/components/CustomSelect/index.ts
- frontend/tailwind.config.js
- tailwindcss 유틸 추가
- Background 컴포넌트 수정
- CustomSelect 컴포넌트 구현
tailwindcss를 사용하면서 w-full h-full 그리고 w-screen w-screen을 같이 사용할 일이 빈번했음
그래서 아래의 유틸을 추가함.
```ts
({ addUtilities }) => {
const sizeUtil = {
'.flex-all-center': {
justifyContent: 'center',
alignItems: 'center',
},
'.w-h-full': {
width: '100%',
heght: '100%',
},
'.w-h-screen': {
width: '100vw',
height: '100vh',
},
};
addUtilities(sizeUtil);
},
```
Background 아래에 children을 넣을 때 style을 absolute로 주지 않으면 뒤로 가려졌음
그래서 배경과 children을 분리함
아래 형식의 options를 넣어주면 select가 그려지고
```tsx
export interface CustomSelectOptions {
value: string;
label: string;
selected?: boolean;
}
```
onChange 함수를 넣어주면 value와 label을 인자로 넣어줌.
```tsx
interface CustomSelectProps {
options: CustomSelectOptions[];
required?: boolean;
autoFocus?: boolean;
onChange?: ({ …
```
> Fe/feature/#175 custom select 구현

- .dockerignore
- .github/workflows/docker-cd.yml
- Dockerfile.nginx
- Dockerfile.node
- config/nginx/default.conf
- docker-compose.yml
GitHub Actions로 docker CD 자동화 구현하기
(nginx와 node 이미지를 따로 띄우기 위해 docker-compose를 사용했다)
[[타로밀크티 기술 블로그] GitHub Actions로 CI/CD 자동화하기](https://www.notion.so/GitHub-Actions-CI-CD-6c607b37cea24e5db0b20a39e30df154)
**1️⃣ 502 Bad Gateway,,,**
`docker-compose.yml` 에 따라 node와 nest 컨테이너가 실행된다. 하지만 `http://sever_ip:8080` 으로 접속한 결과, `502 Bad Gateway`를 띄웠다.
**2️⃣ nest 어플리케이션이 동작하지 않는다,,,**
`502 Bad Gateway`가 떴다는 것은 nginx가 잘 동작하고 있음을 의미하므로 nest 어플리케이션 실행을 확인하기 위해 다음 커맨드를 실행했다.
```bash
curl http://localhost:3000
Failed to connect to localhost port 3000: Connection refused
```
**3️⃣ 도커 컨테이너를 확인해보자,,,**
Docker Compose로 띄운 컨테이너 중 node 컨테이너에서 다음과 같은 오류가 발생했다. `cd6024be7c28` 는 `docker ps -a` 로 조회한 node 컨테이너 ID다.
```bash
docker logs cd6024be7c28
> backend@0.0.1 start:prod
> node dist/main
[Nest] 19  - …
```
> Be/feature/#191 docker 배포 자동화

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/components/Buttons/CustomButton.tsx
- frontend/src/tailwind.css
resolve #218 
- Mac인지 Window인지에 따라 다른 스타일 지정
- 커스텀 커서가 화면 밖으로 넘어가면 생기는 스크롤 바 제거
- 채팅 길어질 때 생기는 스크롤바도 제거 마우스 스크롤로 대화 스크롤 가능
`detect-browser` 라이브러리 사용해서 os가 뭔지 알아냄
```typescript
import { detect } from 'detect-browser';
const browser = detect();
const __MAC__ = browser?.os?.includes('Mac');
const sizeMap: Record<string, string> = {
s: `h-40 display-bold14 ${__MAC__ ? 'leading-18' : ''} p-8 min-h-0`,
m: `h-50 display-bold16 ${__MAC__ ? 'leading-20' : ''} p-16`,
l: `h-60 display-bold16 ${__MAC__ ? 'leading-30' : ''} p-16`,
};
```
> Fe/bugfix/#218 mac과 윈도우에서 다르게 보이는 UI 수정

- .github/workflows/docker-cd.yml
- Dockerfile.nest
- Dockerfile.nginx
- Dockerfile.was
- config/nginx/default.conf
- docker-compose.yml
- SSL 인증서 발급
- HTTPS 적용
[[타로밀크티 기술 블로그] HTTPS 적용하기](https://www.notion.so/HTTPS-a12766a4bbae4aaab356cda4cf8148e5) 
[[타로밀크티 기술 블로그] 521 Web server is down](https://www.notion.so/521-Web-server-is-down-9f0707e307ea4915b655e715fddc9db5)
SSL/TLS 인증서를 발급 받기 위해 Let's Encrypt의 무료 오픈소스를 이용했다.
```bash
certbot --nginx --domains [your_domain]
```
인증서를 발급받으면 각종 키들이 생성되고 다음과 같은 문구가 출력된다.
```bash
Set the `server_name` directive to use the Nginx installer.
```
앞에서 나온 문구를 참고하여 NGINX 설정 파일에 SSL 설정 및 도메인 이름을 적용한다.
- [expose가 동작하지 않았던 이유 찾기](https://github.com/boostcampwm2023/web09-MagicConch/pull/254#issuecomment-1825928764)
- [ERR 521: Web Server is down 해결하기](https://github.com/boostcampwm2023/web09-MagicConch/pull/254#issuecomment-1825954568)
> Be/feature/#253 도메인 https 적용

- .github/workflows/docker-cd.yml
resolved #256 
파일 내용을 따옴표로 감싸 줄바꿈 문자가 유지되도록 수정
`newline.txt` 파일이 있다고 가정해보자.
```
1st line
2nd line
3rd line
```
하나는 따옴표 없이, 하나는 따옴표로 감싸서 파일을 생성한다.
```bash
#!/bin/bash
echo $(cat newline.txt) > without-quotes.txt # 따옴표 없이 파일 생성
echo "$(cat newline.txt)" > with-quotes.txt # 따옴표로 감싸서 파일 생성
```
- `without-quotes.txt` : 줄바꿈 뒤에 공백 문자가 하나 더 붙은 형태
```
1st line
2nd line
3rd line
```
- `with-quotes.txt` : `newline.txt`와 동일하나 맨 마지막에 줄바꿈이 하나 더 붙은 형태
```
1st line
2nd line
3rd line
```
> Be/bugfix/#256 SSL 파일 생성 오류

- .github/workflows/docker-cd.yml
resolved #262 
SSL 파일 생성 시, 부모 디렉토리 먼저 생성하도록 수정
SSL 파일 생성 도중에 다음과 같은 에러가 발생했다.
```
config/nginx/ssl/options-ssl-nginx.conf: No such file or directory
Error: Process completed with exit code 1.
```
파일 생성 전에 `mkdir -p`를 사용하여 부모 디렉토리가 없다면 생성하도록 수정했다.
> `-p` : 모든 부모 디렉토리를 생성해라
> Be/bugfix/#262 백엔드 배포 깃허브 액션 오류

- frontend/src/business/hooks/useSocket.ts
- frontend/src/pages/HomePage/HomePage.tsx
resolve #250 
- home에서 connectSocket reconnect 옵션 추가해서 기존 소켓이 이미 존재할 경우, 기존 연결을 끊고 새로 연결하게 함.
- socket 에러 시 (aichatpage에서 새로고침 시에 연결이 끊겨 socket을 찾을 수 없음) home으로 이동하도록 함
뒤로 갔다가 다시 aichat으로 이동하는 경우
aichat에서 새로고침하는 경우
> Fe/bugfix/#250 aichatpage 새로고침을 하거나 뒤로갔다가 다시 왔을 때 제대로 동작 안하는 버그

- frontend/src/components/Popup/PasswordPopup.tsx
- frontend/src/components/Popup/Popup.tsx
- frontend/src/components/Popup/index.tsx
resolve #171
resolve #14
- Popup component 작성함.
- PasswordPopup component 작성함.
**1️⃣ Popup component**
```typescript
interface PopupProps {
close: () => void;
onCancel?: () => void;
onConfirm?: () => void;
children: React.ReactNode;
}
```
- onCancel, onConfirm: `취소하기`, `확인하기` 버튼 클릭 시  실행할 이벤트를 설정 할 수 있다.
사용 예시
```typescript
const showPopup = () => {
open(({ close }) => <Popup close={close}>상담자에게 타로카드가 펼쳐집니다.</Popup>);
};
```
**2️⃣ PasswordPopup component**
```typescript
interface PasswordPopupProps {
close: () => void;
onCancel?: () => void;
defaultValue?: string;
onSubmit: (password: string) => void;
}
```
- defaultValue: 기본 비밀번호 값  
참고) defaultValue가 설정되어있는지 여부에 따라 텍스트가 다름.  
`<div>비밀번호를 {defaultValue ? '설정' : '입력'}하세요</div>`
사용 예시
```typescript
const showPopup = () => {
open(({ close …
```
> Fe/feature/#14,#171 팝업창 UI 구현

- frontend/src/components/Buttons/IconToggleButton.tsx
- frontend/src/components/Buttons/index.ts
- frontend/src/components/ProfileSetting/DeviceSelect.tsx
- frontend/src/components/ProfileSetting/DeviceToggleButtons.tsx
- frontend/src/components/ProfileSetting/ProfileSetting.tsx
- frontend/src/components/ProfileSetting/index.tsx
- frontend/src/components/ProfileSettingOverlay/ProfileSettingOverlay.tsx
- frontend/src/components/ProfileSettingOverlay/index.ts
resolve #176
- ProfileSetting 컴포넌트 작성
- IconToggleButton 컴포넌트 추가
**기존 IconButton을 활용해서 IconToggleButton 작성함**
```typescript
import { ButtonSize } from './CustomButton';
import IconButton from './IconButton';
interface IconToggleButtonProps {
activeIcon: string;
disabledIcon: string;
iconSize?: number;
buttonSize?: ButtonSize;
onClick?: () => void;
active: boolean;
}
export default function IconToggleButton({
activeIcon,
disabledIcon,
iconSize,
buttonSize,
onClick,
active,
}: IconToggleButtonProps) {
return (
<IconButton
icon={active ? activeIcon : disabledIcon}
iconSize={iconSize}
iconColor={active ? 'textWhite' : 'textDefault'}
buttonSize={buttonSize}
buttonColor={active ? 'active' : 'cancel'}
onClick={onClick}
circle
/>
);
}
```
> Fe/feature/#176 프로필 설정 팝업 UI 구성 & IconToggleButton 추가

- frontend/src/components/BackgroundMusic/BackgroundMusic.tsx
- frontend/src/tailwind.css
resolve #255 
- 재생 버튼 위에서 커서가 활성화 되었는데도 음악 재생 클릭이 되지 않는 문제 해결
- 외부 버튼 보다 숨겨진 audio의 재생 버튼이 작아서 생기는 문제
- 둘의 크기를 맞춰서 해결함
> fix: audio 재생 input 크기와 외부 버튼 크기 맞추기

- frontend/src/App.tsx
- frontend/src/business/hooks/useDataChannel.ts
- frontend/src/business/hooks/useHumanChat/useHumanChatMessage.ts
- frontend/src/business/hooks/useHumanChat/useHumanTarotSpread.ts
- frontend/src/constants/events.ts
- frontend/src/pages/HumanChatPage/HumanChatPage.tsx
resolve #261
- WebRTC의 데이터 채널을 사용해 채팅을 주고 받는 기능 구현
**1️⃣ useWebRTC()의 반환 값 중  `chatChannel`을 사용해서 HumanChatPage 채팅 기능 hook을 연결함**
```typescript
export default function HumanChatPage() {
const { roomName } = useParams();
const webRTCData = useWebRTC(roomName as string);
const [tarotId, setTarotId] = useState<number>();
// TODO: {requestTarotCard}로 받아 '타로 카드 펼치기' 버튼을 눌렀을 때 실행
const {} = useHumanTarotSpread(webRTCData.chatChannel, setTarotId);
const { messages, onSubmitMessage, inputDisabled } = useHumanChatMessage(webRTCData.chatChannel, tarotId, setTarotId);
return (
<Background type="dynamic">
<Header
rightItems={[
<SideBar key="chat-side-bar">
<ChatContainer
width="w-400"
height="h-4/5"
position="top-40"
messages={messages}
onSubmitMessage={onSubmitMessage}
inputDisabled={inputDisabled} …
```
> Fe/feature/#261 데이터 채널을 사용해 채팅을 주고 받을 수 있어야 함

- backend/signal/src/events.js
- backend/signal/src/server.js
- frontend/src/business/hooks/useControllMedia.ts
- frontend/src/business/hooks/useRTCPeerConnection.ts
- frontend/src/business/hooks/useSignalingSocket.ts
- frontend/src/business/hooks/useSocket.ts
- frontend/src/business/hooks/useWebRTC.ts
- frontend/src/pages/HumanChatPage/ChattingPage.tsx
- frontend/src/pages/HumanChatPage/HumanChatPage.tsx
- 방을 생성한 사람에게 권한 부여
- 게스트가 방을 나가면 그냥 나가짐
- 호스트가 방을 나가면 게스트의 방도 닫힘
아래와 같이 방을 생성할시 users 객체에 role: 'host'를 추가함으로써 권한을 부여해줌
```js
export function createRoom(socket, password) {
...
users[userID] = { roomID, role: 'host' };
...
}
```
그리고 방에 들어올 경우 users 객체에 role: 'guest'를 추가해줌.
```js
export function joinRoom(socket, roomID, password) {
...
users[userID] = { roomID, role: 'guest' };
...
```
만약 role이 gust인데 방을 나가면 그냥 호스트에게 userExit 이벤트를 전달하고  
다음 연결을 위해 데이터 채널 커넥션을 초기화 시켜줌  
다른 사용자는 기존의 데이터 채널을 사용할 수 없고, 재협상이 필요하기 때문  
```js
export function disconnectSocket(socket) {
...
if (role === 'guest') {
socketRooms[roomID].users = socketRooms[roomID].users.filter(_userID => _userID !== userID);
socket.to(roomID).emit('userExit', { id: socket.id });
}
...
}
```
호스트가 방을 나가면 방 자체가 제거 돼야 하기 때문에 delete로 …
> Fe/feature/#63#83 호스트가 종료시 방 닫힘

- backend/was/src/chat/chat.controller.ts
- backend/was/src/chat/chat.service.ts
- backend/was/src/chat/dto/chatting-message-response.dto.ts
- backend/was/src/chat/dto/chatting-room-response.dto.ts
- backend/was/src/chat/dto/create-chatting-message.dto.ts
- backend/was/src/chat/dto/update-chatting-room.dto.ts
- backend/was/src/common/constants/etc.ts
- backend/was/src/events/create-dto-helper.ts
- backend/was/src/events/events.gateway.ts
- backend/was/src/events/type.ts
- backend/was/src/tarot/dto/create-tarot-result.dto.ts
- backend/was/src/tarot/dto/tarot-card-response.dto.ts
- backend/was/src/tarot/dto/tarot-result-response.dto.ts
- backend/was/src/tarot/tarot.service.ts
resolved #318 
DTO 생성 방법 변경
지난 주 멘토링 때, DTO의 필드를 일일이 대입하는 것에 대해 피드백을 받았다. 필드를 일일이 대입하게 되면 중간에 필드를 빼먹는 실수를 할 수도 있고, 필드를 변경했을 때 모든 곳에서 이를 수정해야 한다는 문제가 있다. 
따라서 이를 해결하기 위해 DTO 내에 static 메서드를 만들었다. `fromEntity()`로 DTO를 생성하는 생성자 함수를 흉내냈다. 추가적으로 DTO는 데이터 전달용 객체이므로 `readonly`도 붙여줬다. 
```ts
export class ChattingMessageResponseDto {
@IsUUID()
@ApiProperty({ description: '채팅 메시지 ID', required: true })
readonly id: string;
@IsBoolean()
@ApiProperty({ description: '호스트 여부', required: true })
readonly isHost: boolean;
@IsString()
@ApiProperty({ description: '채팅 메시지', required: true })
readonly message: string;
static fromEntity(entity: ChattingMessage): ChattingMessageResponseDto {
return { ...entity };
}
}
```
```diff
async findMessagesById(id: string): Promise<ChattingMessageResponseDto[]> {
const …
```
> Be/refactor/#318 dto 수정

- backend/signal/src/events/events.gateway.ts
- backend/was/src/chat/chat.controller.ts
- backend/was/src/common/constants/apis.ts
- backend/was/src/common/decorators/swagger/chat.decorator.ts
- backend/was/src/common/decorators/swagger/decorator.ts
- backend/was/src/common/decorators/swagger/factory/decorator.factory.ts
- backend/was/src/common/decorators/swagger/factory/interface.factory.ts
- backend/was/src/common/decorators/swagger/interface.ts
- backend/was/src/common/decorators/swagger/tarot.decorator.ts
- backend/was/src/tarot/tarot.controller.ts
커스텀 데코레이터를 활용하여 비즈니스 로직에 좀 더 집중할 수 있도록 리팩토링
API를 짜기 시작했던 주부터 swagger로 인해 코드가 많이 지저분해졌다고 느꼈다. API 문서화는 간편해서 좋았지만, 그만큼 코드가 너무 지저분해져 비즈니스 로직을 찾기 힘들었다.
피어세션에서 커스텀 데코레이터를 이용해 swagger를 깔끔하게 정리하신 분이 계셔서 내 나름대로 swagger를 위한 커스텀 데코레이터를 만들었다.
<br>
**Step 1️⃣ 커스텀할 데코레이터 선정하기**
커스텀 데코레이터를 작성하기 전에 코드를 지저분하게 만드는 swagger 데코레이터들을 선별했다. `@ApiTag()` 처럼 컨트롤러 단에 붙는 데코레이터는 굳이 커스텀할 필요가 없었다. (어차피 한 줄이다)
문제는 바로 함수 앞에 붙는 수많은 데코레이터다. 비즈니스 로직보다 데코레이터의 라인 수가 훨씬 많다.
```ts
@Get('ai')
@ApiOperation({ summary: '채팅방 목록 조회 API' })
@ApiOkResponse({
description: '채팅방 목록 조회 성공',
type: [ChattingRoomResponseDto],
})
@ApiUnauthorizedResponse({ description: '인증 받지 않은 사용자' })
async findRooms(@Req() req: Request): Promise<ChattingRoomResponseDto[]> {
return await this.chatService.findRoomsById(req.cookies.magicConch);
}
```
따라서 함수 …
> Be/refactor/#313 커스텀 데코레이터

- frontend/src/business/hooks/useAiChat/useAiChatMessage.ts
- frontend/src/business/hooks/useTOLD.tsx
resolve #329 
- [told](https://www.told.club/)를 사용할 때 custom event이 제대로 발생하게 수정함.
- told 쪽의 개발자 문서에서 커스텀 이벤트(피드백 폼이 보여지는 조건)를 어떻게 사용해야 하는 지 잘 나와있지 않았음.
- 그래서 개발자 측에 메일을 보냄
- 답변이 왔다..!
- 조언해준 대로 수정해주었다 👍
```typescript
import useOverlay from './useOverlay';
export default function useTOLD(event: 'AI' | 'HUMAN') {
const global = window as any;
const { open } = useOverlay();
const displayTold = () => {
global.dataLayer.push({ event });
open(({ close }) => {
const interval = setInterval(() => {
const container = document.querySelector('#told-container');
if (container && !container.innerHTML) {
return;
}
close();
clearInterval(interval);
}, 1000);
return (
<div className="w-h-screen flex-with-center">
<span className="loading loading-spinner loading-lg"></span>
</div>
);
});
};
return { …
```
> Fe/bugfix/#329 useTOLD 커스텀 이벤트 작동하게 수정

- frontend/src/@types/close.d.ts
- frontend/src/business/hooks/useBlocker.ts
- frontend/src/business/hooks/usePopup/useExitPopup.tsx
- frontend/src/business/hooks/useWebRTC/useWebRTC.ts
- frontend/src/components/Popup/Popup.tsx
- frontend/src/pages/HumanChatPage/ChattingPage.tsx
- 팝업 닫기 누를 시 뒤로 가지지 않던 버그 수정
- 프로필 재설정 할 때마다 비밀번호 재입력 하던 버그 수정
close #369 
close #374
close #380 
close #386
> Fe/bugfix/#386 경로,팝업관련 버그수정

- .github/workflows/blue-green-cd.yml
- backend/deploy.sh
- backend/docker-compose.blue.yml
- backend/docker-compose.green.yml
resolved #401 
이미지를 삭제하지 않으면 새로운 작업 내역이 반영되지 않는 문제가 발생했다. 이를 해결하기 위해 이미지가 새롭게 생성되는지 봤는데 새롭게 빌드를 해도 기존 이미지가 유지되고 있는 것을 발견했다.
**깃헙 해시를 이미지 태그로 사용하여 버전관리를 하도록 수정!!**
<br>
아래는 수정 전의 코드다.
```yml
run: |
cd backend
docker builder prune -a -f
docker system prune -f
cp docker-compose.blue.yml docker-compose.${{ github.sha }}.blue.yml
docker-compose -f docker-compose.${{ github.sha }}.blue.yml build --no-cache -t "${{ secrets.DOCKER_USERNAME }}/magicconch:latest-blue"
```
놀랍게도 저 짧은 코드에 오류가 세 가지나 있다.
1. `docker builder`, `docker system` 필요없다.
2. `--no-cache`도 필요없다.
3. `-t`도 동작하지 않는다.
처음에는 도커 캐시의 문제인 줄 알고 `docker builder prune -a -f` 같은 명령어를 사용했다. `--no-cache`도 썼지만 다 무용지물이었다.
저 코드 자체도 태그를 이용한 버전 관리가 제대로 되진 않지만 `-t`도 동작하지 않는다. docker cli에서 `-t`는 빌드한 이미지에 이름과 태그를 부여한다. 따라서 docker-compose도 똑같을 줄 알았다. …
> Be/bugfix/#401 깃헙 액션 배포 이슈

- backend/Dockerfile.signal
- backend/Dockerfile.was
- backend/config/nginx/default.conf
- backend/signal/src/main.ts
- backend/was/src/main.ts
resolved #362 
- STUN/TURN 서버 라우팅을 위해 nginx 설정 파일 수정
- graceful shutdown을 위한 설정 추가
<br>
coturn이라는 오픈소스를 활용하여 STUN/TURN 서버를 구축했다. 
> [!NOTE]
> coturn은 NAT 환경에서의 P2P 통신을 돕기 위한 클라이언트 간 데이터 전달 (= TURN) 및 공인 IP와 포트 정보를 제공 (=STUN) 한다.
현재 서버용 인스턴스를 하나만 이용하고 있기 때문에 서버에게 독립적인 공간을 제공하기 위해 도커 컨테이너로 띄우기로 결정했다. (프로젝트 일관성도 한 몫함..)
도커 컨테이너를 띄우기 전에 coturn 이미지를 다운로드 한다.
```bash
docker pull coturn/coturn
``` 
다음 명령어로 `coturn-server` 컨테이너를 띄운다. 이때, `expose`를 사용하여 nginx 컨테이너를 통한 접속만 허용한다. (외부에서 포트번호로 직접 접속 불가!!) 보안을 위해 `USER`와 `PASSWORD`도 작성해줬다.
```
docker run -d
--expose 3478 \
--name coturn-server \
-e TURN_SERVER_NAME=[server_name] \
-e TURN_SERVER_USER=[server_user] \
-e TURN_SERVER_PASSWORD=[server_password] \
coturn/coturn
```
```
CONTAINER ID   IMAGE                  COMMAND                  CREATED …
```
> Be/feature/#362 stun/turn 서버 구현

- .github/workflows/blue-green-cd.yml
- backend/docker-compose.blue.yml
- backend/docker-compose.green.yml
resolved #414 
호스트 서버에서 바로 도커 명령어로 컨테이너를 띄웠는데 이를 삭제하고 `docker-compose` 파일에 서비스로 작성해줬다.
```yml
coturn-server:
image: "coturn/coturn"
container_name: "coturn-server"
environment:
- TURN_SERVER_NAME=${TURN_SERVER_NAME}
- TURN_SERVER_USER=${TURN_SERVER_USER}
- TURN_SERVER_PASSWORD=${TURN_SERVER_PASSWORD}
expose:
- "3478"
```
> Be/bugfix/#414 stun/turn 접근

- frontend/src/components/Select/Select.tsx
- 카메라, 오디오 변경이 제대로 됨
- 미디어 option이 변경 될 때마다 강제로 0번째를 선택하도록 되어있었음..
- 이를 초기에만 수행하도록 변경함
```diff
useEffect(() => {
-  if (options.length) setSelected(options[0]);
+  if (options.length && !selected.value && !selected.label) {
+    setSelected(options[0]);
+  }
}, [options]);
```
https://github.com/boostcampwm2023/web09-MagicConch/assets/43428643/c949aa79-2a77-4b76-9af8-4bfc092c20bd
> FE/bugfix/#404 카메라,오디오 변경 제대로 안됨

- frontend/src/business/hooks/useWebRTC/useRTCPeerConnection.ts
- frontend/src/constants/urls.ts
- frontend/src/vite-env.d.ts
- 기존 구글서버 주소 지우고 백엔드 서버의 주소로 변경함.
> FE/feature/#410 TURN/STUN 서버 연결

- frontend/src/business/hooks/useWebRTC/useControllMedia.ts
- host 방에 혼자 있을 때 미디어 toggle 시 발생하는 에러 수정
- 들어오기 전의 미디어 상태 반영 안됨 문제 해결
(host가 방 생성 -> 카메라나 마이크 킴 -> 상담자가 들어옴 -> host가 카메라/마이크 끈 걸로 인식했음)
```typescript
if (!mediaInfoChannel.current || mediaInfoChannel.current.readyState !== 'open') return;
```
```typescript
useEffect(() => {
if (!mediaInfoChannel.current) return;
mediaInfoChannel.current.addEventListener('open', () => {
const audioTrack = localVideoRef.current?.srcObject as MediaStream;
const videoTrack = localVideoRef.current?.srcObject as MediaStream;
mediaInfoChannel.current?.send(
JSON.stringify([{ type: 'audio', onOrOff: audioTrack.getAudioTracks()[0].enabled }]),
);
mediaInfoChannel.current?.send(
JSON.stringify([{ type: 'video', onOrOff: videoTrack.getVideoTracks()[0].enabled }]),
);
});
}, [mediaInfoChannel.current]);
```
> Fe/bugfix/#416 #417 host 방에 혼자 있을 때 미디어 toggle 시 에러 들어오기 전의 미디어 상태 반영 안됨

- frontend/src/business/hooks/useSpeakerHighlighter.ts
- frontend/src/utils/unit8Array.ts
- speaker highlighter가 소리 인식을 너무 쉽게 하는 문제 개선
더하기만하고 배열 길이대로 나누질 않았다.. 코파일럿만 믿지말고 코드를 꼭 확인하는 습관을 가져야겠다..
- 일정 볼륨 이하는 그림자 표시를 하지 않도록 0으로 처리해주었고, 최대 볼륨으로 나누고 최대 그림자 길이로 나눠서 적절한 그림자 길이를 계산해주는 함수를 만들어뒀다.
```typescript
function getShadowLength(volume: number) {
const thresholdedVolume = Math.max(volume - THERESHSHOLD, 0);
return (thresholdedVolume / (MAX_VOLUME - THERESHSHOLD)) * MAX_SHADOW_LENGTH;
}
```
> Fe/bugfix/#408 speaker highlighter가 소리 인식을 너무 쉽게 하는 문제

- backend/was/src/app.module.ts
- backend/was/src/auth/auth.module.ts
- backend/was/src/common/config/cache/cache.module.ts
- `CacheConfigModule` 전역으로 사용하도록 수정
- `useFactory` 타입 오류 수정
단순 코딩 실수,,
> Be/bugfix/#463 redis 연결 실패

- backend/was/package.json
- backend/was/src/chat/chat.service.spec.ts
- backend/was/src/chat/chat.service.ts
- backend/was/src/members/members.servcie.spec.ts
- backend/was/src/members/members.service.ts
- backend/was/src/mocks/chat/chatting-message.mocks.ts
- backend/was/src/mocks/chat/chatting-room.mocks.ts
- backend/was/src/mocks/chat/index.ts
- backend/was/src/mocks/members/index.ts
- backend/was/src/mocks/members/member.mocks.ts
- backend/was/src/mocks/socket/socket.mocks.ts
- backend/was/src/mocks/tarot/index.ts
- backend/was/src/mocks/tarot/tarot-card.mocks.ts
- backend/was/src/mocks/tarot/tarot-result.mocks.ts
- backend/was/src/socket/socket.service.spec.ts
- backend/was/src/socket/socket.service.ts
- backend/was/src/tarot/tarot.controller.ts
- backend/was/src/tarot/tarot.service.spec.ts
- backend/was/src/tarot/tarot.service.ts
- backend/was/tsconfig.build.json
resolved #469 
- `tarot`, `chat` 단위 테스트 변경사항 적용
- `members` 단위 테스트 작성
추후 소켓 통신에서 로그인 정보를 받아와서 그에 따른 분기 처리가 필요하다. 일단 의사 코드를 주석으로 남겨놓고, 협의 후에 이를 반영할 예정이다.   
서비스 수정 사항을 반영하여 다시 테스트 코드를 작성했다.
| `chatService` | `tarotService` |
| --- | --- |
| ![image](https://github.com/boostcampwm2023/web09-MagicConch/assets/70785620/ddc915e9-8486-4c90-8909-f28a5b866f48) | ![image](https://github.com/boostcampwm2023/web09-MagicConch/assets/70785620/3fb182e0-c7c1-4d6e-b305-d66f148c073f) |
> Be/refactor/#469 단위 테스트

- backend/was/src/tarot/tarot.controller.ts
- 변수명, 파라미터명을 직관적으로 변경하는 과정에서 일부만 수정하여 유효성 검사 에러 발생
- :id -> :cardNo 로 변경하여 일치하도록 수정
```diff
- @Get('card/:id')
+ @Get('card/:cardNo')
@FindTarotCardDecorator(
'타로 카드 이미지',
{ type: 'integer', name: 'cardNo' },
TarotCardDto,
)
async findTarotCardByCardNo(
@Param('cardNo', ParseIntPipe) cardNo: number,
): Promise<TarotCardDto> {
return await this.tarotService.findTarotCardByCardNo(cardNo);
}
```
> Be/bugfix/#485 findTarotCardByCardNo

- .github/workflows/blue-green-cd.yml
- backend/compose.blue-deploy.yml
- backend/compose.green-deploy.yml
- backend/deploy.sh
- `start-prod` 오타 수정 : `start_prod`
- `deploy.sh` 실패 시 곧바로 스크립트 종료하도록 설정
- `deploy.sh`의 결과를 바탕으로 슬랙 알림 보내도록 설정
```bash
#!/bin/bash
set -e 
ERR_MSG=''
trap 'echo "Error occured: $ERR_MSG. Exiting deploy script."; exit 1' ERR
....
DOCKER_COMPOSE_FILE="compose.$RUN_TARGET-deploy.yml"
sudo docker-compose -f "$DOCKER_COMPOSE_FILE" pull || { ERR_MSG='Failed to pull docker image'; exit 1; }
sudo docker-compose -f "$DOCKER_COMPOSE_FILE" up -d || { ERR_MSG='Failed to start docker image'; exit 1; }
...
sudo docker exec $NGINX_ID /bin/bash -c "nginx -s reload" || { ERR_MSG='Failed to reload nginx'; exit 1; }
...
```
```yaml
- name: Run a New Version of the application on Remote Server
uses: appleboy/ssh-action@master
with:
host: ${{ secrets.SSH_HOST }}
username: ${{ secrets.SSH_USERNAME }}
key: ${{ …
```
> Be/bugfix/#488 도커 healthcheck

- frontend/src/business/hooks/useOverlay/useOverlay.spec.tsx
- useOverlay 로직에 대해 renderHook을 사용해 테스트코드 작성 완료
useOverlay는 오버레이를 추가하고, 닫는 훅임
그래서 이 두가지 동작이 제대로 되는지에 대해 테스트를 진행함.
방법은 두가지가 있었음 실제로 테스트 컴포넌트를 작성하고, 안에서 제대로 동작이 되는지 보는것과
react testing library가 제공하는 renderHook 메서드를 사용하는것.
굳이 테스트코드를 위한 테스트컴포넌트를 작성할정도로 복잡한 로직도 아니고
다른 훅을 의존하지 않기에 renderHook 메서드를 사용함
이 때 waitFor을 사용했는데 waitFor는 변경된 결과를 기다릴 때 사용하라고 문서에 가이드가 있었음 [링크](https://testing-library.com/docs/dom-testing-library/api-async/#waitfor)
그래서 act로 유저의 액션을 동기적으로 일으킴 [링크](https://testing-library.com/docs/preact-testing-library/api/#act) 그래서 리렌더링 되면 act 메서드 다음줄로 넘어가게 됨
closed #502
> FE/feature/#502 useOverlay훅 테스트코드 작성

- frontend/src/@types/close.d.ts
- frontend/src/business/hooks/useBlocker.ts
- frontend/src/business/hooks/useOverlay/types.tsx
- frontend/src/business/hooks/useOverlay/useOverlay.spec.tsx
- frontend/src/business/hooks/useOverlay/useOverlay.tsx
- frontend/src/business/hooks/usePopup/useExitPopup.tsx
- frontend/src/business/hooks/usePopup/useLoginPopup.tsx
- frontend/src/business/hooks/usePopup/usePasswordPopup.tsx
- frontend/src/business/hooks/useTOLD.tsx
- frontend/src/business/hooks/useTarotSpread/useDisplayTarotCard.tsx
- frontend/src/business/hooks/useTarotSpread/useHumanTarotSpread.tsx
- frontend/src/business/hooks/useTarotSpread/useTarotSpread.tsx
- frontend/src/business/hooks/useWebRTC/useDataChannel.eventListeners.ts
- frontend/src/business/hooks/useWebRTC/useSignalingSocket.spec.ts
- frontend/src/business/hooks/useWebRTC/useSignalingSocket.ts
- frontend/src/components/Popup/PasswordPopup.tsx
- frontend/src/components/Popup/Popup.tsx
- frontend/src/components/TarotSpread/TarotSpread.tsx
- frontend/tsconfig.json
- 해당 이슈 해결
- vi undefined 오류 해결
원인은 최소 버튼을 누를시 window.close() 메서드가 호출되기 때문이었음.
즉, 함수의 파라미터로 close를 받았지만 정작 함수 안에서 구조분해 할당할 때 이를 사용하지 않아서 생기는 문제...
```tsx
function Component({value}: {close: () => void; value: string}) {
const handler = () => {
// ⚠️ window.close() 호출됨!
close();
};
return ...
}
```
그래서 close라고 적혀있는 메소드명을 전부 closeXXX open이라고 적혀있는 메소드들은 openXXX라고 바꿔줌
나중에 close 키워드를 함수 이름으로 써야할 때 주의해야함
그리고 window.close는 원래 window.open으로 열린 페이지에 대해서만 작동한다고함
그래서 로컬 환경에서는 작동하지 않았는데 왜 배포하면 이 메서드가 작동하는지는 아직 찾아보는중
아래처럼 __mocks__ 폴더 안에 있는 가짜모듈을 테스트 코드가 아닌 실제 코드에서 import해서 사용하고 있어서 생겼던 에러
```tsx
import WebRTC from '@business/services/__mocks__/WebRTC';
```
그래서 tsconfig.json에서 exclude 옵션으로 `__mocks__` 폴더를 제외 해주려고 했는데
그러면 테스트 코드를 작성 할 때도 vi를 찾지 못하는 문제가 생겨버림 어떻게 해야할지 생각  해 봐야할듯
> FE/bugfix/#432 채팅방개설 취소시 튕기는버그

- frontend/src/pages/HumanChatPage/ChattingPage.tsx
- 더이상 화면을 공유하는 화면에서 나의 목소리가 들리지 않음
대화할 때 내 목소리가 들리면 오히려 신경이 쓰이므로 자신의 목소리는 설정 페이지에서만 들리도록 수정함
간단하게 `<video>` 의 volume을 0으로 설정하면 됐음
close #435
> FE/bugfix/#435 설정창에서만 내 목소리가 들리도록 수정함

- backend/was/src/auth/__mocks__/kakao.auth.service.ts
- backend/was/src/auth/auth.controller.ts
- backend/was/src/auth/service/auth.service.spec.ts
- backend/was/src/auth/service/auth.service.ts
- backend/was/src/auth/service/kakao.auth.service.ts
- backend/was/src/chat/chat.service.spec.ts
- backend/was/src/chat/chat.service.ts
- backend/was/src/chat/chatting-info.interface.ts
- backend/was/src/chat/entities/chatting-message.entity.ts
- backend/was/src/chat/entities/chatting-room.entity.ts
- backend/was/src/common/constants/etc.ts
- backend/was/src/members/dto/create-member.dto.ts
- backend/was/src/members/entities/member.entity.ts
- backend/was/src/tarot/dto/tarot-card.dto.ts
- backend/was/src/tarot/entities/tarot-card.entity.ts
- backend/was/src/tarot/entities/tarot-result.entity.ts
- backend/was/src/tarot/tarot.service.spec.ts
- backend/was/src/tarot/tarot.service.ts
- backend/was/test/chat.e2e-spec.ts
- backend/was/test/tarot.e2e-spec.ts
- 커버링 인덱스를 활용하기 위해 정말 필요한 컬럼만 조회하도록 수정
- 불필요한 쿼리 삭제 (ex. `save`시 `INSERT` 후 `SELECT`가 수행됨)
- 트랜잭션 오버헤드 방지
- 데이터 타입 수정
mysql은 기본적으로 `AUTOCOMMIT`이 1로 설정되어 있다. 이로 인해 개별 sql문이 트랜잭션으로 취급되고 트랜잭션의 시작과 끝에 오버헤드가 발생하여 성능이 저하될 수 있다.
따라서 연관된 쿼리를 하나의 트랜잭션으로 묶어 오버헤드를 줄여줄 것이다. 다음 코드는 한 번에 여러 개의 쿼리를 일괄로 실행하는 함수인데, 트랜잭션을 사용하지 않아 각각의 `save` 작업이 개별적인 트랜잭션으로 처리된다. 실행 시 약 395 밀리초가 소요된다.
```ts
async saveMessages(
room: ChattingRoom,
createMessageDtos: CreateChattingMessageDto[],
): Promise<void> {
const startTime = new Date();
for (const createMessageDto of createMessageDtos) {
const message: ChattingMessage = ChattingMessage.fromDto(
createMessageDto,
room,
);
await this.chattingMessageRepository.save(message);
}
const endTime = new Date();
const diff = endTime.getTime() - startTime.getTime(); …
```
> Be/feature/#522 데이터베이스 최적화

- .github/workflows/add-issue-to-project-automatically.yml
- .github/workflows/configure-pr-automatically.yml
🔮 resolved #532
일단 문제가 되는 부분 삭제
- 프로젝트 url이 `https://github.com/orgs/boostcampwm2023/projects/19`여서 프로젝트 ID가 `19`라고 판단
- 하지만 `19`는 프로젝트의 number일 뿐 ID는 이와 다른 값임
**1️⃣ 프로젝트 ID 조회하기**
프로젝트 아이디를 조회하고자 `github.rest.projects.listForOrg`와 `github.rest.project.listForRepo`를 사용했다. 각각 프로젝트가 속한 organization, repository를 조회한다.
- `listForOrg`
```ts
const projects = await github.rest.projects.listForOrg({
org,
}); // status: 200, data: []
```
- `listForRepo`
```ts
const projects = await github.rest.projects.listForRepo({
owner,
repo,
}); // status: 200, data: []
```
둘 다 200번 응답을 반환하지만 `data` 컬럼이 빈 배열로 와 프로젝트 ID를 조회할 수 없었다.
**2️⃣ 개발자 도구를 열어서 프로젝트 ID 찾기**
무식한 방법으로 프로젝트 ID를 찾는데 성공했다. 이를 깃헙 시크릿에 추가하여 `column`을 조회하는 데 집어넣었다.
```ts
const columns = await github.rest.projects.listColumns({
project_id: …
```
> Devops/bugfix/#532 pr 라벨 설정 및 이슈 상태 변경 오류

- frontend/src/business/hooks/sidebar/useSidebar.tsx
- frontend/src/components/aiChatPage/ChatLogContainer/ChatLogContainer.tsx
- frontend/src/components/common/Background/Background.tsx
- frontend/src/components/common/ChatContainer/ChatContainer.tsx
- frontend/src/components/common/Header/Header.tsx
- frontend/src/components/common/Header/HeaderRight.tsx
- frontend/src/components/common/Header/index.ts
- frontend/src/pages/AIChatPage/AIChatPage.tsx
- frontend/src/pages/HomePage/HomePage.tsx
- frontend/src/pages/HumanChatPage/HumanChatPage.tsx
- frontend/src/utils/random.ts
🔮 resolved #524
- Sidebar 문제 완전히 해결
**처음에 생각했던 문제** -> 상대방이 접속하면 상태가 바뀌고 화면이 리렌더링됨
근데 리렌더링 되는데 `왜?` 오른쪽으로 스크롤이 되지 에 대한 문제때문에 시간이 많이 소요됨
그래서 상태 변경을 없애버렸는데도 불구하고 동일한 문제가 반복돼서 html문제라 생각하게됨
원인은 자식요소에 `display:absolute` `left: 100%` 을 주고서 부모가 다시 리렌더링 됐을 때
화면이 오른쪽 끝으로 스크롤됨. 모든 요소에 overflow:hidden을 줘도 동일한 증상이 반복됨
웃긴건 아예 오른쪽 끝으로 이동되는게 아니라 왼쪽을 조금 남기고 이동함
원인은 찾았는데 이게 왜 원인인지는 아직 이유를 찾지 못해서 1.0 배포 후 이유를 찾을 예정
https://github.com/boostcampwm2023/web09-MagicConch/assets/43428643/46e60ebd-264f-48cb-a15e-6c1cba345afd
https://github.com/boostcampwm2023/web09-MagicConch/assets/43428643/f83825d2-6496-4801-a5a1-d0c316646162
> Fe/bugfix/#524 sidebar 관련버그 수정

- .github/workflows/configure-pr.yml
🔮 resolved #549
액션을 트리거할 때 `opened`에 대해서만 트리거 되도록 설정
```yaml
on:
pull_request:
types: ["opened", "edited"]
```
PR이 열리거나 수정되면 액션이 트리거되도록 했는데 PR을 설정하는 과정이 곧 PR을 수정하는 작업이기 때문에 작업이 멈추지 않았다.
즉, 액션이 PR을 수정할 때마다 또 다른 액션을 트리거 하게 된다. 따라서 `edited`를 제거하여 이를 해결했다.
```diff
on:
pull_request:
-    types: ["opened", "edited"]
+    types: ["opened"]
```
> Devops/bugfix/#549 pr 설정 액션이 멈추지 않음

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
🔮 resolved #555
- `release` 브랜치로 푸시되었을 때 릴리즈 노트 초안을 작성하는 액션 작성
- 릴리즈 노트 초안을 위한 설정파일 작성
[release-drafter](https://github.com/release-drafter/release-drafter?tab=readme-ov-file)를 참고하여 다음과 같이 작성했다.
```yaml
name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
template: |
$CHANGES
footer: |
$CONTRIBUTORS
categories:
- title: "🚀 Features"
collapse-after: 15
labels:
- "feature"
- title: "🐛 Bug Fixes"
collapse-after: 15
labels:
- "bug"
- title: "🛠️ Improvement"
collapse-after: 15
labels:
- "refactor"
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
change-title-escapes: '\<*_&#/@[]'
...
replacers:
- search: "/$(Be|Fe|Devops|Be,fe|Fe,be)/"
replace: "[$1]"
- search: "/(feature|bugfix|hotfix|refactor)(,(feature|bugfix|hotfix|refactor))/"
replace: "[$1$2]"
- search: "/"
replace: " " …
```
> Devops/feature/#555 release drafter 도입

- .github/workflows/blue-green-cd.yml
- backend/Dockerfile.nginx
- backend/compose.blue-deploy.yml
- backend/compose.green-deploy.yml
🔮 resolved #565
- SSL 인증서 갱신
- 매월 SSL 인증서를 자동으로 갱신하는 스케줄링 작성
- 볼륨을 연결하여 SSL 관련 파일 복사 과정 삭제
`net::ERR_CERT_DATE_INVALID` 에러를 해결하기 위해 SSL 인증서를 갱신했다. 기존에 작성한 docker-compose의 명령이 올바르지 않아 자동으로 갱신이 이루어지지 않았다.
docker-compose의 커맨드를 수정하는 것도 하나의 방법이지만, 매번 강제로 갱신을 하게 되면 갱신 횟수를 초과할 수 있기 때문에 호스트 서버에 certbot을 설치하여 ssl 인증서를 발급 받았다.
```bash
sudo apt install certbot
sudo certbot certonly \
--webroot --webroot-path=/var/www/certbot \
--email [email] \
--agree-tos \
--no-eff-email \ 
-d [domain]
```
위 명령을 실행하고 나면 `/etc/letsencrypt` 하위에 `keys`, `live` 등이 생긴다.
`options-ssl-nginx.conf`과 `ssl-dhparams.pem`도 생성하여 보안을 고려해줬다.
```
sudo openssl dhparam -out /etc/ssl/certs/ssl-dhparams.pem 2048
```
이제 더 이상 `net::ERR_CERT_DATE_INVALID` 에러가 발생하지 않는다.
```
0 2 1 * * sudo certbot certonly --non-interactive --force-renewal …
```
> Be/bugfix/#565 ssl 인증서 만료

- backend/was/src/auth/__mocks__/kakao.auth.service.ts
- backend/was/src/auth/service/kakao.auth.service.ts
- backend/was/src/chat/chat.service.spec.ts
- backend/was/src/chat/chat.service.ts
- backend/was/src/common/constants/apis.ts
- backend/was/src/common/constants/errors.ts
- backend/was/src/exceptions/codemap/auth-codemap.ts
- backend/was/src/exceptions/codemap/chat-codemap.ts
- backend/was/src/exceptions/codemap/index.ts
- backend/was/src/exceptions/codemap/tarot-codemap.ts
- backend/was/src/exceptions/codemap/type.ts
- backend/was/src/exceptions/custom-exception.ts
- backend/was/src/exceptions/index.ts
- backend/was/src/exceptions/metadata.ts
- backend/was/src/tarot/tarot.service.spec.ts
- backend/was/src/tarot/tarot.service.ts
- backend/was/test/auth.e2e-spec.ts
🔮 resolved #569
- 커스텀 에러를 위한 인터페이스 정의
- 모듈별 커스텀 에러 코드 정의
- 커스텀 에러 적용에 따른 테스트 파일 수정
[kakao developers](https://developers.kakao.com/docs/latest/ko/kakaologin/trouble-shooting)를 참고하여 커스텀 에러를 작성했다. 커스텀 에러는 다음 구조를 갖는다.
```ts
export interface ExceptionMetadata {
status: number;        // HTTP 응답 코드
message: string;       // HTTP 에러 메시지
code: string;          // 커스텀 에러 코드
description?: string;  // 에러에 대한 부연설명
}
```
사용자에게는 `message`만 표기하여 민감한 정보를 노출하지 않고, 개발자는 고유한 에러 코드를 통해 원인을 빠르게 파악할 수 있다. 아래는 에러코드의 예시다. 사용자에게는 `로그인 실패`에 대한 메시지만 전달하여 구체적인 에러에 대한 정보를 노출하지 않는다.
```ts
export const AUTH_CODEMAP: ExceptionCodemap = {
KAKAO_TOKEN_REQUEST_FAILED: {
status: 400,
message: '카카오 로그인에 실패했습니다.',
code: 'MAE001',
description: '카카오 토큰 발급에 실패했습니다.',
},
...
}
```
고유 에러코드의 명명 규칙인 다음과 같다. 카카오의 경우, `KOE001` 형태의 …
> Be/refactor/#569 api 커스텀 에러 정의

- backend/Dockerfile.nginx
🔮 resolved #478
- `COPY --link`로 원본 파일에 대한 하드링크를 생성하여 원본 파일을 가리키도록 설정
- 이전에는 복사본을 만들었다면 이번에는 원본 파일을 가리켜 저장공간을 절약
> [!NOTE]
> `was`와 `signal`은 소스코드가 포함된 이미지를 레지스트리에 푸시하기 때문에 링크를 활용할 수 없었다. `--link`를 활용하기 위해서는 원격 서버(EC2)에 모든 소스코드가 들어있어야 하는데 이는 도커의 장점을 활용하지 못한다고 판단했다.
> Devops/refactor/#478 ci cd 워크플로우 개선

- backend/was/src/socket/socket.service.ts
> Be/refactor/#589 타로 해설 채팅 기록에 저장 안하기

- frontend/.eslintrc.cjs
- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/business/hooks/auth/useKakaoOAuthRedirect.ts
- frontend/src/utils/env.ts
🔮 resolved #584
- 클라이언트에서 서버에 로그인 요청 시 SameSite 헤더 설정을 추가함.
```
This attempt to set a cookie via a Set-Cookie header was blocked because it had the "SameSite=Lax" attribute but came from a cross-site response which was not the response to a top-level navigation.
```
로그인을 하는 과정에서 위와 같은 경고 문구가 떴음.
이는 현재 클라이언트에서 서버로 로그인 요청을 보낼 때 서버가 쿠키 설정을 해주게 되는데
지금은 요청의 헤더의 `SameSite` 속성이 기본 값인 `Lax`로 설정되어 있기 때문이다.
`SameSite=Lax`는 보안 상의 이유로 쿠키 전송을 일부 제한하는데, 다른 사이트에서 쿠키 설정을 하려고 하면 차단하게 된다...
그래서 `localhost` 설정에서는 정상적으로 동작했지만, `web09-magicconch.pages.dev`와 `was.magicconch.com`끼리에서는 제대로 동작하지 않았던 것이다.
```diff
const res = await axios.get(KAKAO_LOGIN_URL, {
params: { code },
withCredentials: true,
+      headers: {
+        SameSite: 'None',
+        Secure: true,
+      },
});
```
ex) 베이스 브랜치에 포함되기 위한 코드는 모두 …
> Fe/bugfix/#584 최초 로그인 시 카카오톡 로그인 후 쿠키가 붙지 않음

- .github/workflows/blue-green-cd.yml
- backend/Dockerfile.nginx
- backend/was/package.json
- backend/was/src/auth/service/auth.service.spec.ts
- backend/was/src/chat/chat.service.spec.ts
- backend/was/src/chat/chat.service.ts
- backend/was/src/chat/entities/chatting-message.entity.ts
- backend/was/src/chat/entities/chatting-room.entity.ts
- backend/was/src/common/types/socket.ts
- backend/was/src/socket/socket.service.ts
- backend/was/src/tarot/tarot.service.ts
- backend/was/test/chat.e2e-spec.ts
🔮 resolved #587
채팅 메시지 조회 시 카드도 같이 조회하도록 수정
→ `body[-1]` : 타로 결과 / `body[-2]` : 타로 카드 이미지 url
```json
[
{ 
"isHost": true, 
"message": "어떤 고민이 있어?"
},
{ 
"isHost": false, 
"message": "오늘 운세를 알고 싶어"
},
{
"isHost": true,
"message": "https://kr.object.ncloudstorage.com/magicconch/basic/0.jpg"
},
{ 
"isHost": true, 
"message": "0번 카드에 대한 해설입니다."
}
]
```
> Be/bugfix/#587 채팅 메시지 조회 시 카드도 같이 보여야 함

- backend/was/.eslintrc.js
- backend/was/jest-e2e.config.js
- backend/was/jest-unit.config.js
- backend/was/jest.config.js
- backend/was/jest.config.json
- backend/was/package.json
- backend/was/src/auth/dto/auth-status.dto.ts
- backend/was/src/auth/service/auth.service.spec.ts
- backend/was/src/auth/service/auth.service.ts
- backend/was/src/chat/chat.service.spec.ts
- backend/was/src/chat/chat.service.ts
- backend/was/src/chat/dto/chatting-message.dto.ts
- backend/was/src/chat/dto/chatting-room.dto.ts
- backend/was/src/chat/dto/update-chatting-room.dto.ts
- backend/was/src/exceptions/codemap/members-codemap.ts
- backend/was/src/members/dto/create-member.dto.ts
- backend/was/src/members/dto/member.dto.ts
- backend/was/src/members/members.controller.ts
- backend/was/src/members/members.decorators.ts
- backend/was/src/members/members.module.ts
- backend/was/src/members/members.service.spec.ts
- backend/was/src/members/members.service.ts
- backend/was/src/tarot/dto/tarot-result.dto.ts
- backend/was/src/tarot/tarot.service.spec.ts
- backend/was/src/tarot/tarot.service.ts
- backend/was/test/jest-e2e.json
- backend/was/test/members.e2e-spec.ts
🔮 resolved #598
**1️⃣ 쿠키 정보(jwt)를 바탕으로 사용자 정보 조회하기**
**2️⃣  단위 테스트, e2e 테스트를 위한 설정 중복 해결**
- 공통 설정 정보가 담긴 `jest.config.json` 작성
- 단위 테스트를 위한 설정 파일을 불러오는 `jest-unit.config.js` 작성
- e2e 테스트를 위한 설정 파일을 불러오는 `jest-e2e.config.js` 작성
```js
const commonJestConfig = require('./jest.config.json'); // 공통 설정 불러오기
module.exports = (target) => {
if (target === 'unit') { // for 단위 테스트
return {
...commonJestConfig,
testRegex: '.*\\.spec\\.ts$',
};
}
if (target === 'e2e') { // for e2e 테스트
return {
...commonJestConfig,
testRegex: '.e2e-spec.ts$',
};
}
return commonJestConfig;
};
```
```json
{
"nickname": "타로밀크티", // 필수항목
"profileUrl": "https://kr.object.ncloudstorage.com/magicconch/basic/0.jpg", // 선택항목 (undefined 가능)
}
```
> Be/feature/#598 사용자 api 및 서비스 구현

- backend/was/src/auth/auth.controller.ts
- frontend/src/business/hooks/auth/useKakaoOAuth.ts
- frontend/src/business/hooks/auth/useKakaoOAuthRedirect.ts
- frontend/src/components/aiChatPage/ChatLogContainer/ChatLogContainer.tsx
- frontend/src/components/common/Buttons/KakaoLoginoutButton.tsx
- frontend/src/components/common/Header/Header.tsx
- frontend/src/constants/kakao.ts
- frontend/src/pages/AIChatPage/AIChatPage.tsx
🔮 resolved #602
- Ai 채팅 페이지에 로그아웃 버튼 추가
> Fe/feature/#602 카카오톡 로그아웃 기능
