frontend/.eslintrc.js, frontend/.storybook/main.ts, frontend/.storybook/preview.ts, frontend/package.json, frontend/pnpm-lock.yaml
- storybook 설정을 완료했습니다.
- [storybook 사용 예시](https://season-broccoli-784.notion.site/storybook-4b9a94eba41d48f5b58c08b6e102ad52?pvs=4)
- [storybook 공식 문서](https://storybook.js.org/docs/react/writing-stories/introduction)
```
npm run storybook
```
=> feature/#105-feat: storybook 설정

.github/workflows/close-issue-automatically.yml
=> chore: ref를 추가하지 않아서 그 부분 추가

.github/workflows/close-issue-automatically.yml
issue 아래에 하위 issue가 없을 경우의 처리
하위 이슈가 없을경우 match, map이 실행되지 않도록 변경함.
=> fix: 하위 이슈가 없을 경우 처리해줌

.github/workflows/close-issue-automatically.yml
하위 issue가 없을 경우의 처리
처음부터 배열을 만들고, 해당 배열에 하위 이슈들을 넣어줌으로 문제 해결함
=> fix: issue가 없을 경우 정말로 처리해줌

.github/workflows/random-review-assign.yml
- Assinees 자동지정
- Reviewers 3명중 랜덤지정
자신의 닉네임을 제외하고 남은 세명중 랜덤하게 두명을 뽑아 리뷰어로 지정함.
이를위해 `hkusu/review-assign-action@v1.3.1` 사용
resolved #118
=> feat: 리뷰어 지정 자동화 + assinees 지정 자동화

frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/App.tsx, frontend/src/components/BackgroundMusic/BackgroundMusic.tsx, frontend/src/components/BackgroundMusic/index.ts, frontend/src/pages/HomePage/HomePage.tsx
resolve #22 
- 브금 파일 요청을 위한 axios 설치
- 받아온 브금 url을 연결해서 재생
- 처음에는 노래가 꺼져있고, 클릭해서 노래를 켤 수 있음
- 무한 반복 재생
<br>
시도 1️⃣: 해당 사이트의 네트워크 탭에서 얻을 수 있는 blob 링크 활용하기 
- 실제 파일을 URL.createObjectURL(blob);으로 링크를 만들었을 때만 유효한 링크
- 이미 만들어진 blob:~ 링크를 audio 태그 src에 넣어줘도 작동하지 않음
시도 2️⃣: 해당 파일을 요청하는 API를 찾아서 파일 링크를 받아옴 
- autoplay 기능 활용 시 "DOMException: play() failed because the user didn't interact with the document first" 에러 발생
- 브라우저에서는 사용자가 의도하지 않은 소리 재생을 막는 것을 기본 원칙으로 함
- 즉 자동 재생 기능은 사용할 수 없음
시도 3️⃣: controls 설정으로 재생 버튼이 포함된 컨트롤러 기능을 활용
- 화면에 보이는 UI가 마음에 들지 않음
- 재생 버튼 부분만 사용하기 위해 그 부분만 잘라내고 나머지는 overflow:  hidden 처리를 해둠
- 재생 버튼은 opacity 0으로 숨겨두고 실제로 사용하고자하는 아이콘 이미지를 뒤에 넣어주었음
- 음악이 켜지면 onPlay 콜백이 불리고, 음악이 꺼지면 onPause 콜백이 호출됨 -> played 상태값에 변화를 줘서 아이콘 이미지 변경
시도 4️⃣: 페이지를 이동해도 음악이 유지되도록 App.js로 BGM 컴포넌트를 이동 …
=> Fe/feature/#22 bgm 컴포넌트 구현

frontend/src/App.tsx, frontend/src/pages/HomePage/HomePage.tsx
- 메인 화면에서 버튼 클릭 시 /chat/ai, /chat/human 으로 이동하기
=> feature: 라우터 수정 및 url 이동

backend/src/members/entities/member.entity.ts, backend/src/tarot/entities/tarot-card.entity.ts, backend/src/tarot/entities/tarot-result.entity.ts
=> Be/bugfix/#138 타로 오타 수정

frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/pages/HomePage/HomePage.tsx, frontend/src/socket.ts, socket-server/.gitignore, socket-server/babel.config.json, socket-server/nodemon.json, socket-server/package.json, socket-server/pnpm-lock.yaml, socket-server/src/server.js
resolve #24 
- home 화면에서 'ai에게 타로보기' 버튼을 누르면 서버와 socket 연결
- node로 임시 socket server를 구현함.
- frontend/src 에 socket 연결 관련해서 `socket.ts`를 만들었는데 관련 로직을 어느 폴더에 넣어야 할 지 모르겠음
=> Fe,be/feature/#24 socket.io를 통해서 방을 생성

frontend/src/components/Background/Background.tsx, frontend/src/components/ChatList/ChatList.tsx, frontend/src/pages/HomePage/HomePage.tsx
=> bugfix: 소라고둥 위치 조정

backend/src/events/events.gateway.ts, frontend/src/components/ChatList/ChatList.tsx, frontend/src/components/MessageBox/MessageBox.tsx, frontend/src/main.tsx, frontend/src/pages/AIChatPage/AIChatPage.tsx, frontend/src/pages/HomePage/HomePage.tsx
resolve #156 
- socket으로 받아 온 메세지 & client에서 보내는 메세지 chatList에 뜨도록 수정함.
```typescript
useEffect(() => {
setMessageEventListener(message => addMessage('left', message));
}, []);
```
위처럼 작성한 useEffect가 2번 발생해버리는 문제가 있었다
```typescript
ReactDOM.createRoot(document.getElementById('root')!).render(
<React.strictMode>
<OverlayProvider>
<BrowserRouter>
<App />
</BrowserRouter>
</OverlayProvider>
</React.strictMode>,
);
```
`<React.strictMode>`에서는 2번 실행이 된다! 삭제해주었더니 해결됐다
=> Fe/feature/#156 socket으로 받아 온 메세지 chat list에 띄우기

frontend/src/components/BackgroundMusic/BackgroundMusic.tsx, frontend/src/components/ChatInput/ChatInput.tsx, frontend/src/components/CustomButton/CustomButton.tsx, frontend/src/components/MessageBox/MessageBox.tsx, frontend/src/pages/AIChatPage/AIChatPage.tsx, frontend/src/pages/HomePage/HomePage.tsx
- circle 타입 추가
- size 설정은 Props 넣을 필요 x
- 대신 Icon 컴포넌트에서 text-20 이런식으로 설정해줘야함
- <img width="244" alt="image" src="https://github.com/boostcampwm2023/web09-MagicConch/assets/69742775/3609ec98-34bc-46ae-be2b-1c9df8a7c9d4">
- transparent 타입 버튼 스타일 수정 => 호버링 시 배경 및 보더 색상 강조 제거 
- 모든 버튼 호버링 시 110%로 스케일 업
<br>
=> Fe/feature/#162 공통 컴포넌트 보완

frontend/package.json, frontend/pnpm-lock.yaml, frontend/public/mockServiceWorker.js, frontend/src/main.tsx, frontend/src/mocks/browser.ts, frontend/src/mocks/handlers.ts, frontend/src/stores/queries/getHelloQuery.ts, frontend/tsconfig.json
1. msw 설정
2. react query 설정
- msw 설정할 때 아래 워닝이 뜸
> [MSW] Warning: intercepted a request without a matching request handler
이유는 MSW는 모든 요청을 가로채기 때문. 하지만 모두 정의할수는 없기에
worker.start를 할 때 onUnhandledRequest 옵션을 `bypass`로 줘서
미들웨어에서 처리되지 않는 요청은 그대로 브라우저로 전달되도록 함.
- msw 사용법 
/src/mocks/handlers.ts 파일에서 http.get 등의 메서드를 추가해 핸들러를 추가하면 됨.
=> Fe/#165 msw&react query setting

.github/workflows/basic-cd.yml, backend/src/members/members.module.ts, backend/src/members/members.service.ts
- nginx를 사용한 CD 스크립트 작성
- 저번 PR에 누락된 사용자 관련 모듈, 서비스 추가
nginx를 사용하기 위해 ncp 서버에 nginx 설정을 해줘야 했다.
- nginx 설치
```bash
apt-get install nginx
```
- nginx 사용자 추가
```
adduser --system --no-create-home --disabled-login --group nginx
chown -R nginx:nginx /etc/nginx
```
- nginx 설정 파일 작성
```text
user nginx;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;
events {
worker_connections 1024;
}
http {
server {
listen 80;
location / {
proxy_pass http://localhost:3000;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection 'upgrade';
proxy_set_header Host $host;
proxy_cache_bypass $http_upgrade;
}
access_log /var/log/nginx/nest-app-access.log;
error_log /var/log/nginx/nest-app-error.log;
}
}
```
위의 설정 파일로 인해 주소창에 …
=> Be/feature/#177 GitHub actions를 활용하여 배포 자동화

backend/package-lock.json, backend/package.json, backend/src/chat/chat.service.spec.ts, backend/src/chat/chat.service.ts
기존에 작성한 채팅 서비스 `ChatService`에 대한 단위 테스트 코드 작성
테스트 코드 실행 시, `'cannot find module'` 에러가 발생했다. 이를 해결하기 위해 `package.json`에 다음 코드를 추가했다.
```diff
"jest": {
+    "moduleDirectories": [
+      "node_modules",
+      "src"
+    ],
"moduleFileExtensions": [
"js",
"json",
"ts"
],
"rootDir": "src",
"testRegex": ".*\\.spec\\.ts$",
"transform": {
"^.+\\.(t|j)s$": "ts-jest"
},
"collectCoverageFrom": [
"**/*.(t|j)s"
],
"coverageDirectory": "../coverage",
"testEnvironment": "node",
+    "moduleNameMapper": {
+      "src/(.*)": "<rootDir>/$1"
+    }
}
```
- `moduleDirectories` :  모듈을 탐색할 때 검색할 디렉토리 지정
- `moduleNameMapper` : 모듈 경로를 매핑하는 데 사용
=> Be/feature/#204 채팅 서비스 단위 테스트

frontend/src/business/hooks/useOverlay/useOverlay.tsx, frontend/src/business/hooks/useShareButtons.ts, frontend/src/components/Buttons/IconButton.tsx, frontend/src/components/TarotSpread/TarotSpread.tsx, frontend/src/constants/colors.ts, frontend/tailwind.config.js
- IconColor 수정
- tailwindcss에 kakao-icon 색상 추가
- 안쓰는 변수, import, 함수 제거
- 배포 전 수정
=> fix: build할 때 에러나는 부분 수정

backend/src/events/stream.ts, frontend/package.json, frontend/src/components/ChatList/ChatList.tsx, frontend/src/components/MessageBox/MessageBox.tsx, frontend/src/main.tsx, frontend/src/tailwind.css
- `pnpm run prod` 실행 시 msw 비활성화
- 이미지 더블 클릭 시 파랗게 변하는 부분 fix
- server에서 stream parsing 과정에서 message undefined 에러 fix
=> Fe/feature/#235 todo 처리하고 qa 진행해서 버그 수정

backend/src/events/events.gateway.ts, backend/src/main.ts
CORS 정책 수정
- 서버 어플리케이션 CORS 수정
```diff
async function bootstrap() {
const app = await NestFactory.create(AppModule);
+  app.enableCors({
+    origin: '*',
+    methods: 'GET,HEAD,PUT,PATCH,POST,DELETE',
+    credentials: true,
+  });
...
}
bootstrap();
```
- 웹소켓 CORS 수정
```diff
@WebSocketGateway({
+  cors: { origin: '*' },
-  cors: { origin: 'localhost:5173' },
})
```
=> Be/bugfix/#238 cors 에러 수정

frontend/index.html, frontend/src/components/TarotSpread/TarotSpread.tsx, frontend/tailwind.config.js
=> Fe/feature/#234 다크모드/라이트모드 UI 일치

frontend/src/components/Buttons/CustomButton.tsx
- 호버링 시 글씨색 진하게 수정
- 변경 전
<br>
- 변경 후
=> feat: 호버링 글씨 색상 진하게 변경

frontend/src/business/hooks/useAiChat/useAiChatMessage.ts, frontend/src/components/MessageBox/Message.tsx, frontend/src/components/MessageBox/MessageBox.tsx
resolve #226 
- 로딩 컴포넌트 추가
- 피드백보기 버튼 위치 이동
```여전히 클로바가 고장날 때가 종종 있는 것 같아🥲 (영상 확인)```
https://github.com/boostcampwm2023/web09-MagicConch/assets/69742775/3ea75e31-b8f8-4389-acfd-47004a31a8bb
=> feat: loading daisy component 추가

frontend/src/business/hooks/useHumanChat/index.ts, frontend/src/business/hooks/useHumanChat/usePasswordPopup.tsx, frontend/src/pages/HomePage/HomePage.tsx, frontend/src/utils/ramdom.ts
resolve #15
resolve #67
- 홈 화면에서 `방 생성하기` 버튼을 누르면 비밀번호 설정창이 뜬다.
- 비밀번호 설정창에는 랜덤으로 생성된 default 값이 들어간다. 
**usePasswordPopup() 훅 작성**
```typescript
export default function usePasswordPopup() {
const { open } = useOverlay();
type PasswordPopupOptions = {
host?: boolean; // true면 랜덤으로 default 값 지정됨.
};
const defaultOptions: PasswordPopupOptions = {
host: false,
};
const openPasswordPopup = (setPassword: (password: string) => void, options = defaultOptions) => {
const defaultValue = options.host ? randomString() : '';
open(({ close }) => (
<PasswordPopup
close={close}
onSubmit={setPassword}
defaultValue={defaultValue}
/>
));
};
return { openPasswordPopup };
}
```
**랜덤으로 비밀번호 default 값 생성 (코파일럿이 짜줌)**
```typescript
export function randomString(length: number = 8) {
const chars = …
```
=> Fe/feature/#15 #67 암호 입력 팝업 랜덤 생성 페이지 이동

frontend/src/App.tsx, frontend/src/components/CamContainer/CamContainer.tsx, frontend/src/components/ProfileSetting/ProfileSetting.tsx, frontend/src/pages/HumanChatPage/ChattingPage.tsx, frontend/src/pages/HumanChatPage/SettingPage.tsx
- Page 상단에 Provider 추가해줌
1. Provider 상위에 연결
2. 상태들을 각 컴포넌트에 맞도록 연결
=> Feat/bugfix/#291 머지후 문제

backend/was/src/logger/winston/winston.transports.ts
=> Be/bugfix/#302 import 오류

frontend/src/business/hooks/useShareButtons.ts, frontend/src/business/services/Kakao.ts, frontend/src/vite-env.d.ts
- ✅ 카카오 공유
- ✅ 링크 복사
- ⛔️ 이미지 다운로드
> [!NOTE]
> 이미지 다운로드 기능은 차후 기능으로 추가 예정
=> Fe/bugfix/#252 공유기능 버그 수정

frontend/src/business/hooks/useAiChat/useAiChatMessage.ts, frontend/src/business/hooks/useTOLD.tsx
resolve #301 
- told 요청 시 로딩 애니메이션 추가
- custom event 활용해서 수정해보려다가 정보가 없어 실패 -> 일단 told 측에 메일로 물어봄
**useTOLD() 훅 작성**
- 아직 displayTold()을 했다고 told 창이 뜨지는 않음.. 하지만 일단 told 창이 뜰 때까지 로딩 뜨게 해둠
- 현재 told 창이 뜨는 원리는 `피드백하기`라고 적혀있는 버튼을 눌렀을 때가 트리거임.
=> FE/feature/#301 told 요청 후 로딩바 표시

.github/workflows/blue-green-cd.yml, backend/deploy.sh, backend/docker-compose.blue.yml, backend/docker-compose.green.yml, backend/signal/src/main.ts, backend/was/src/main.ts
정적으로 포트 번호를 지정해놓고 변경했더니 빌드 과정이 필요했고, 그로 인한 module not found가 발생했다.
아주 쉬운 방법을 두고 돌고 돌았다.. 
도커 컴포즈 파일이 블루, 그린 두 종류가 있기 때문에 그냥 거기다 실행할 포트 번호를 집어넣어주면 된다.
```diff
version: "3.3"
services:
was-blue:
build:
context: .
dockerfile: Dockerfile.was
environment:
...
+      - PORT=3000
expose:
- "3000"
volumes:
- /var/log/was:/app/was/logs
signal-blue:
build:
context: .
dockerfile: Dockerfile.signal
+    environment:
+      - PORT=3001
expose:
- "3001"
...
```
이제 포트번호를 전환하면서 실행 중이던 어플리케이션을 종료할 필요도 없다.
=> Be/bugfix/#364 무중단 배포

frontend/src/business/hooks/useChatMessage/useHumanChatMessage.ts
-  #343 에서 message 전달 방식이 string이 아닌 object 형식으로 바뀌었는데 메세지를 화면에 띄우는 과정에서 그 부분이 적용이 안되었었음
=> fix: datachannel message 전달 방식 수정

frontend/src/components/ChatContainer/ChatList/ChatList.tsx
- AI 스트림 응답 시 자동 스크롤 내려갈 때 위아래로 진동하면서 흔들리는 문제 해결
- ❓ 원인: `scroll-smooth` 설정 때문이었다.
부드럽게 스크롤 되는 효과와  AI의 답변을 토큰 단위로 가져와 말풍선이 업데이트되는 부분이 충돌되서 위 아래로 진동되는 문제가 발생했었다. 
그래서  `scroll-smooth` 을 제거해버렸다.
=> FE/bugfix/#383 AI 스트림 응답 시 자동 스크롤 내려갈 때 위아래로 진동하면서 흔들리는 문제 해결

frontend/src/business/hooks/useChatMessage/useAiChatMessage.ts
=> fix: ai 채팅이 끝나고 input이 disabled가 안되는 문제

frontend/src/business/hooks/useChatMessage/useAiChatMessage.ts
=> fix: 피드백 요구 삭제

frontend/src/business/hooks/useTarotSpread/useHumanTarotSpread.tsx, frontend/src/business/hooks/useWebRTC/useSignalingSocket.ts, frontend/src/constants/messages.ts, frontend/src/pages/HumanChatPage/useChattingPageCreateJoinRoomPopup.ts, frontend/src/pages/HumanChatPage/useHumanChatPageWrongURL.ts
=> Fe/bugfix/#422 타로 펼치기 popup 안눌림

.github/workflows/blue-green-cd.yml, backend/signal/package-lock.json, backend/signal/package.json, backend/was/package-lock.json, backend/was/package.json, backend/was/src/common/config/database/database.module.ts, backend/was/src/logger/winston/winston.transports.ts
- 도커 이미지 태그는 달라지지만 계속 같은 이미지 아이디를 사용해서 `--no-cache` 플래그 추가
- winton 로거 타입 오류가 발생하여 해당 부분 타입 수정
- 로컬과 환경이 달라져 entity를 찾지 못하는 문제가 발생하여 주석 처리하여 해결
=> Be/bugfix/#401 도커 캐시 이슈

frontend/src/business/hooks/useOverlay/useOverlay.tsx
- z-index를 10으로 올려줌
z-index가 없어져서 생긴 간단한 문제
=> Fe/bugfix/#444 카드뽑기 UI 버그픽스

frontend/index.html
- viewport의 meta 정보를 바꿔줌.
- 시작스케일, 최대스케일은 1이고 유저가 스케일 조절 못하도록 막는 코드임.
=> FE/bugfix/#447 모바일 input클릭 확대문제

backend/signal/mocks/events/logger.mock.ts, backend/signal/mocks/events/room.mock.ts, backend/signal/mocks/events/socket.mock.ts, backend/signal/mocks/events/user.mock.ts, backend/signal/package-lock.json, backend/signal/package.json, backend/signal/src/events/events.gateway.spec.ts, backend/signal/src/events/events.gateway.ts, backend/signal/src/events/events.module.ts, backend/signal/test/jest-e2e.json, backend/signal/tsconfig.json, frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/@types/close.d.ts, frontend/src/business/hooks/usePopup/usePasswordPopup.tsx, frontend/src/business/hooks/useWebRTC/useSignalingSocket.ts, frontend/src/components/Popup/PasswordPopup.tsx, frontend/src/components/Popup/Popup.tsx, frontend/src/pages/HumanChatPage/useChattingPageCreateJoinRoomPopup.ts, frontend/src/test/setup.ts, frontend/tsconfig.json, frontend/vite.config.ts
- 더 이상 onCancel 함수는 close를 실행 하지 않아도됨 
- close 버튼을 누르면 close가 실행되는게 당연하므로 Popup 컴포넌트에서 close 함수를 받아씀
- onSuccess 콜백에서 close -> closePopup으로 더 명확하게 뭘 닫는지 이름 변경
기존에 onCancel 콜백은 인수로 `close` 함수를 넘겨줬는데 부자연스러웠음
그리고 Popup이 자기 자신을 닫을수도 없었음
그래서 Popup 컴포넌트에 close 함수를 넣어주고, 취소 버튼을 누르면 스스로 닫히도록 수정함
기존에는 콜백함수를 실행시킬 때 그냥 close 함수를 넘겨줬음. 
근데 이 함수를 사용하는 개발자 입장에서는 뭘 닫는지 정확히 파악하기 어렵다고 생각함
그래서 closePopup으로 함수 이름을 변경함
=> FE/refactor/#471 useOverlay 함수 onClose 콜백 리팩토링

.github/workflows/blue-green-cd.yml, backend/Dockerfile.signal, backend/Dockerfile.was, backend/compose.blue-deploy.yml, backend/compose.green-deploy.yml, backend/deploy.sh, backend/signal/src/app.controller.ts, backend/signal/src/app.module.ts, backend/signal/src/main.ts, backend/was/src/app.controller.ts, backend/was/src/app.module.ts, backend/was/src/common/interceptors/errors.interceptor.ts, backend/was/src/main.ts
- 빌드 시간 단축을 위해 `npm install`에서 `npm ci`로 변경
- health check로 어플리케이션이 제대로 동작할 때 트래픽 전환하기
- 슬랙 웹훅을 통해 CI/CD 결과 전달받기
<br>
블루/그린 무중단 배포를 구현했지만, 무중단 배포임에도 불구하고 신규 어플리케이션 실행 중에 에러가 나면 서비스가 중단되는 문제가 발생했다. 이는 단위 테스트로는 감지할 수 없는 오류였다. (`tsconfig.json`, `package.json` 파일의 경로를 수정하면서 진입지점이 달라져 어플리케이션이 실행조차 안되는 에러였다 😂)
기존 스크립트는 어플리케이션 상태를 확인하지 않고 곧바로 트래픽을 전환했다. 즉, 컨테이너가 정상적으로 뜨지 않았더라도 트래픽을 전환하게 된다.
멘토님께 어떤 점을 개선하면 좋을지 여쭤본 결과, health check를 해보라는 답변을 받았다. 어플리케이션이 정상적으로 동작하는지 확인하는 api를 만들고 http 요청을 보내서 이를 확인해보라고 하셨다.
`[origin]/health-check`
```ts
@Controller()
export class AppController {
@Get('/health-check')
healthCheck(): boolean {
return true;
}
}
```
도커에서 health check 명령을 지원하고 있기 때문에 이를 활용하여 구현했다.
- [Dockerfile HEALTHCHECK](https://docs.docker.com/engine/reference/builder/#healthcheck)
- …
=> Be/refactor/#478 ci cd 워크플로우 개선

frontend/src/components/ChatLogContainer/ChatLogContainer.tsx, frontend/src/components/ChatLogContainer/ChatLogList/ChatLogGroup.tsx, frontend/src/components/ChatLogContainer/ChatLogList/ChatLogItem.tsx, frontend/src/components/ChatLogContainer/ChatLogList/ChatLogList.tsx, frontend/src/components/ChatLogContainer/ChatLogList/index.ts, frontend/src/components/ChatLogContainer/NewChatButton.tsx, frontend/src/components/ChatLogContainer/__mocks__/data.ts, frontend/src/components/ChatLogContainer/__mocks__/index.ts, frontend/src/components/ChatLogContainer/index.ts, frontend/src/pages/AIChatPage/AIChatPage.tsx
- 채팅 기록 사이드 바 컴포넌트 작성하기
- 데이터는 간단하게만 만들어놓고 보이는 화면만 집중적으로 구현
=> Fe/feature/#506 채팅 기록 사이드 바 컴포넌트 작성하기

backend/deploy.sh, backend/was/package-lock.json, backend/was/package.json, backend/was/src/app.controller.ts, backend/was/src/app.decorators.ts, backend/was/src/auth/auth.controller.ts, backend/was/src/auth/auth.decorators.ts, backend/was/src/auth/dto/auth-status.dto.ts, backend/was/src/auth/dto/index.ts, backend/was/src/chat/chat.decorators.ts, backend/was/src/chat/chat.service.ts, backend/was/src/main.ts, backend/was/src/tarot/tarot.decorators.ts
resolved #512 
- swagger API 문서를 위한 데코레이터 파일 수정
- swagger 문서 개발환경에서만 확인할 수 있도록 수정
=> Be/refactor/#512 swagger 문서 업데이트

frontend/package.json, frontend/pnpm-lock.yaml
🔮 resolved #534
- tailwindcss 버전이 낮아서 h-dvh가 존재하지 않아서 생겼던 문제
- 윈도우여서 생겼던 문제가 아니었음
- 라이브러리 버전 올리면서 문제 해결
solved #534
=> Fe/bugfix/#534 윈도우에서 height이 맞지 않는 문제 해결

frontend/src/pages/HomePage/HomePage.tsx, frontend/src/pages/HomePage/hooks/index.ts, frontend/src/pages/HomePage/hooks/useReset.ts
🔮 resolved #553
- 그냥 home에서 소켓 연결되어 있는게 있으면 끊어버리게 설정해둠 (`useReset`)
=> Fe/bugfix/#553 홈 화면 갔다가 돌아오면 소켓 에러가 나는 문제

.github/workflows/assert-branch-naming.yml, .github/workflows/configure-pr.yml
🔮 resolved #558
풀리퀘스트 이벤트가 발생할 때마다 [action-branch-name](https://github.com/deepakputhraya/action-branch-name)을 실행한다.
**🌿 브랜치명**
`(1)/(2)/(3)`
1. 분야 : `FE` , `BE` , `DEVOPS`
2. 분류 : `feature` , `bugfix` , `refactor`, `hotfix`
3. 이슈 : `#{이슈 번호}-{이슈 이름}`
=> Devops/feature/#558 브랜치명 강제

frontend/src/business/hooks/sidebar/useSidebar.tsx, frontend/src/components/common/ChatContainer/ChatContainer.tsx, frontend/src/pages/AIChatPage/AIChatPage.tsx
🔮 resolved #552
- chat container padding 값 조정
- sidebar 단독으로 사용할 수 있도록 수정
- 이 경우 메인 컨텐츠는 안 밀림 (ai chat은 공백이 많아서 안 밀리도록 적용함)
- aiChat page 리팩토링함 -> 기존 if문 삭제
=> Fe/bugfix/#552 ai input bar가 작아지는 현상

frontend/src/business/hooks/webRTC/useSignalingSocket.ts, frontend/src/pages/HumanChatPage/hooks/useCreateJoinRoomPasswordPopup.ts
해당 이슈 해결
- 이전에는 guest가 방에 들어가려 시도할 떄 onCancel 콜백을 받지 않았음
- 이를 넣어주고, 초기 화면으로 넘어가도록 추가해줌
=> Fe/bugfix/#575 게스트가 방입장도중 취소 누를시 아무런 작동을 하지않음

backend/was/src/auth/auth.controller.ts
🔮 resolved #584
`sameSite` 값 변경
=> Be/bugfix/#584 최초 로그인 시 카카오톡 로그인 후 쿠키가 붙지 않음

frontend/src/business/hooks/sidebar/useSidebar.tsx, frontend/src/components/common/Background/Background.tsx, frontend/src/components/common/ChatContainer/ChatList/ChatList.tsx, frontend/src/components/common/ChatContainer/MessageBox/Message.tsx, frontend/src/components/common/ChatContainer/MessageBox/MessageBox.tsx, frontend/src/pages/AIChatPage/AIChatPage.tsx, frontend/src/pages/HomePage/HomePage.tsx
🔮 resolved #593
🔮 resolved #594
🔮 resolved #595
🔮 resolved #596
=> Fe/bugfix/#593 #594 #595 #596 UI 버그 픽스

frontend/src/business/hooks/index.ts, frontend/src/business/hooks/popup/useLoginPopup.tsx, frontend/src/business/hooks/useOutSideClickEvent.ts, frontend/src/components/common/Popup/LoginPopup.tsx
=> Fe/feature/#580 Ai 타로보기 버튼 클릭 후 닫을 수 있는 기능
